"""Recreate properties table

Revision ID: 284ee8854a77
Revises: e0334740570d
Create Date: 2023-09-04 11:51:41.258056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284ee8854a77'
down_revision: Union[str, None] = 'e0334740570d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['reset_token'])
    op.create_table(
        'properties',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('street_name', sa.String(100)),
        sa.Column('street_number', sa.String(30)),
        sa.Column('complex_name', sa.String(100)),
        sa.Column('complex_number', sa.String(30)),
        sa.Column('area', sa.String(30)),
        sa.Column('price', sa.BigInteger),
        sa.Column('bedrooms', sa.Integer),
        sa.Column('bathrooms', sa.Numeric(precision=2, scale=1)),
        sa.Column('garages', sa.Integer),
        sa.Column('swimming_pool', sa.Boolean, default=False),
        sa.Column('garden_flat', sa.Boolean, default=False),
        sa.Column('study', sa.Boolean, default=False),
        sa.Column('ground_floor', sa.Boolean, default=False),
        sa.Column('pet_friendly', sa.Boolean),
        sa.Column('link', sa.String(100)),
        sa.Column('link_display', sa.String(30)),
        sa.Column('note', sa.String(255))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
