"""Add reset_token_created_at column to User

Revision ID: 2e8da34fb4af
Revises: 507f1fc94c58
Create Date: 2023-09-04 14:10:50.951063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8da34fb4af'
down_revision: Union[str, None] = '507f1fc94c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
