"""Change price column to BigInteger

Revision ID: 4be089fa241d
Revises: 9f547714be5f
Create Date: 2023-08-09 12:58:35.426055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be089fa241d'
down_revision: Union[str, None] = '9f547714be5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('properties', 'price', type_=sa.BigInteger)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
