"""Initial schema

Revision ID: 65caceef9425
Revises: 2e8da34fb4af
Create Date: 2023-09-07 13:20:40.362362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65caceef9425'
down_revision: Union[str, None] = '2e8da34fb4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('street_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('complex_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('complex_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('area', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('garages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('swimming_pool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('garden_flat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('study', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ground_floor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pet_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('link_display', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='properties_pkey')
    )

    op.create_table('login',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), sa.ForeignKey('users.email'), nullable=True),
    )

    op.create_table('users',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), unique=True, nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.Column('has_access', sa.Boolean(), nullable=True, default=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True, default=False),
    sa.Column('reset_token', sa.String(length=255), unique=True, nullable=True),
    sa.Column('reset_token_created_at', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
