"""Readded backtrace 2

Revision ID: af52b02d10e8
Revises: 7d88e11bd162
Create Date: 2023-08-04 17:41:26.765320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af52b02d10e8'
down_revision: Union[str, None] = '7d88e11bd162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
