"""Increase precision and scale for bathrooms

Revision ID: b4dd7d5bd765
Revises: 7dcff1f74bb9
Create Date: 2023-11-08 13:37:38.926244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd7d5bd765'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE properties ALTER COLUMN bathrooms TYPE NUMERIC(3, 1)")
    op.add_column('properties', sa.Column('prop_type', sa.String(length=255)))
    op.add_column('properties', sa.Column('agent', sa.String(length=255)))
    op.add_column('properties', sa.Column('stand_area', sa.Integer))
    op.add_column('properties', sa.Column('floor_area', sa.Integer))
    op.add_column('properties', sa.Column('carports', sa.Integer))
    op.add_column('properties', sa.Column('prop_category', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
